<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <?php $activeMethodEndOfMonth = Mage::getStoreConfig('payment/pagantis/end_of_month'); ?>
    <?php $discount = Mage::getStoreConfig('payment/pagantis/discount'); ?>
    <?php $activeMethodEndOfMonth = false; ?>
</fieldset>
<div id="payment_form_<?php echo $_code ?>" style="display: none">
    <div id="innerpagantis">
        <?php if($activeMethodEndOfMonth) : ?>
                <input type="radio" class="pagantisradio" name="paymentdetail[]" value="financiacion" checked>Fináncialo con Paga+Tarde

                <div class="PmtSimulator PmtSimulatorSelectable--claim" style="left:-10px; top: 5px;"
                data-pmt-num-quota="4" data-pmt-style="neutral" data-pmt-type="3" data-pmt-discount="<?=$discount?>"
                data-pmt-amount="<?=$this->total?>" data-pmt-expanded="no" data-pmt-max-ins="12"></div>

                <input type="radio" class="pagantisradio" name="paymentdetail[]" value="end_of_month">Paga a fin de mes<br />
        <?php else: ?>
            <input type="hidden" class="pagantisradio" name="paymentdetail[]" value="financiacion">
            <div class="PmtSimulator PmtSimulatorSelectable--claim" style="left:-10px; top: 5px;"
            data-pmt-num-quota="4" data-pmt-style="neutral" data-pmt-type="3" data-pmt-discount="<?=$discount?>"
            data-pmt-amount="<?=$this->total?>" data-pmt-expanded="no" data-pmt-max-ins="12"></div>

        <?php endif; ?>

    </div>
</div>

<style>
    #innerpagantis {margin-left: 20px; height: 50px;}
    .pagantisradio {margin-right:10px}
    #imgpagantisfront {height:20px; margin-right: 10px;}
    #imgpagantisform {height: 30%;width: 30%;margin-left: 20%;}
</style>

<script>
// widget activation
jQuery( document ).ready(function() {
  if (document.getElementsByClassName("pmt_info").length <= 0 ){
    jQuery.getScript("https://cdn.pagamastarde.com/pmt-simulator/3/js/pmt-simulator.min.js");
  }
  pmtSimulator.simulator_app.setPublicKey("<?=$this->public_key?>");
  pmtSimulator.simulator_app.load_jquery();
});
</script>
