<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>
    <?php $discount = Mage::getStoreConfig('payment/pagantis/discount'); ?>
</fieldset>
<div id="payment_form_<?php echo $_code ?>" style="display: none">
    <div id="innerpagantis">
            <input type="hidden" class="pagantisradio" name="paymentdetail[]" value="financiacion">
            <div class="PmtSimulator PmtSimulatorSelectable--claim" style="left:-10px; top: 5px;"
            data-pmt-num-quota="4" data-pmt-style="neutral" data-pmt-type="3" data-pmt-discount="<?=$discount?>"
            data-pmt-amount="<?=$this->total?>" data-pmt-expanded="no" data-pmt-max-ins="12"></div>
    </div>
</div>

<style>
/*<![CDATA[*/
    #innerpagantis {margin-left: 20px; height: 50px;}
    .pagantisradio {margin-right:10px}
    #imgpagantisfront {height:20px; margin-right: 10px;}
    #imgpagantisform {height: 30%;width: 30%;margin-left: 20%;}
    /*]]>*/
</style>

<script>
//<![CDATA[
// widget activation
jQuery( document ).ready(function() {
  pmtSimulator.simulator_app.setPublicKey("<?=$this->public_key?>");
  pmtSimulator.simulator_app.load_jquery();
});
//]]>
</script>
