<div style="text-align: center">
    <?php
      if ($this->iframe) {
    ?>
    <h3><?php echo $this->__('Si no se abre el pop-up haga click al botón para ser redirigido a la página de pago') ?></h3>
    <?php echo $this->getFormRedirect(); ?>
    <?php
  } else {
    ?>
    <h3><?php echo $this->__('Haciendo click en continuar será redirigido a la pasarela de pago seguro de Paga+Tarde.') ?></h3>
     <?php echo $this->getFormRedirect(); ?>
     <?php
        }
     ?>
</div>


<?php
  if ($this->iframe) {
?>

<!-- The Modal -->
<div id="myModal" class="paylater_modal">
  <!-- Modal content -->
  <div class="paylater_modal-content">
    <span id="paylater_close">x</span>
    <iframe id="iframe-pagantis" name="iframe-pagantis" style="width:100%;height:600px;display:block"></iframe>
  </div>
</div>

<script type="text/javascript">
el = document.getElementById("submitButton");
el.addEventListener('click', function (e){
  e.preventDefault();
  document.getElementById('pagantis_pagantis_checkout').setAttribute('target', 'iframe-pagantis');
  document.getElementById('pagantis_pagantis_checkout').submit();
  document.getElementById('iframe-pagantis').style.display = 'block';
  document.getElementById('myModal').style.display = 'block';
});
var closeModal = function closeModal(evt) {
   evt.preventDefault();
   document.getElementById('myModal').style.display = 'none';
 };

 var elements = document.querySelectorAll('#paylater_close, #myModal');
   Array.prototype.forEach.call(elements, function(el){
   el.addEventListener('click', closeModal);
 });
</script>

<script>
document.addEventListener("DOMContentLoaded", function(event) {
    document.getElementById('pagantis_pagantis_checkout').setAttribute('target', 'iframe-pagantis');
    document.getElementById('pagantis_pagantis_checkout').submit();
    document.getElementById('iframe-pagantis').style.display = 'block';
    document.getElementById('myModal').style.display = 'block';
  });
</script>

<?php
  }
?>
