<div style="text-align: center">
    <?php
      if ($this->iframe) {
    ?>
    <h3><?php echo $this->__('Si no se abre el pop-up haga click al botón para ser redirigido a la página de pago') ?></h3>
    <?php echo $this->getFormRedirect(); ?>
    <?php
  } else {
    ?>
    <h3><?php echo $this->__('Haciendo click en continuar será redirigido a la pasarela de pago seguro de Paga+Tarde.') ?></h3>
     <?php echo $this->getFormRedirect(); ?>
     <?php
        }
     ?>
</div>


<?php
if ($this->iframe) {
?>

<div id="paylater_myModal" class="paylater_modal" style="display: none;">
  <div class="paylater_modal-content">
    <iframe id="iframe-pagantis" name="iframe-pagantis" style="width: 100%; height: 100%; display: block" frameborder="0"></iframe>
    <button class="paylater_modal-close" id="paylater_close" title="Cerrar" type="button">X</button>
  </div>
</div>

<script type="text/javascript">
el = document.getElementById("submitButton");
el.addEventListener('click', function (e){
  e.preventDefault();
  document.getElementById('pagantis_pagantis_checkout').setAttribute('target', 'iframe-pagantis');
  document.getElementById('pagantis_pagantis_checkout').submit();
  document.getElementById('iframe-pagantis').style.display = 'block';
  document.getElementById('paylater_myModal').style.display = 'block';
});

var closeModal = function closeModal(evt) {
 evt.preventDefault();
 document.getElementById('paylater_myModal').style.display = 'none';
};

var elements = document.querySelectorAll('#paylater_close, #paylater_myModal');
 Array.prototype.forEach.call(elements, function(el){
 el.addEventListener('click', closeModal);
});

document.addEventListener("DOMContentLoaded", function(event) {
  document.getElementById('pagantis_pagantis_checkout').setAttribute('target', 'iframe-pagantis');
  document.getElementById('pagantis_pagantis_checkout').submit();
  document.getElementById('iframe-pagantis').style.display = 'block';
  document.getElementById('paylater_myModal').style.display = 'block';
  });
</script>

<script type="text/javascript">
(function() {
  function addClass(el, className) {
    if (el.classList){
      el.classList.add(className);
    } else{
      el.className += ' ' + className;
    }
  }
  function removeClass(el, className) {
    if (el.classList) {
      el.classList.remove(className);
    } else {
      el.className = el.className.replace(new RegExp('(^|\\b)' + className.split(' ').join('|') + '(\\b|$)', 'gi'), ' ');
    }
  }

  el = document.getElementById("submitButton");
  el.addEventListener('click', function (e){
    e.preventDefault();
    document.getElementById('pagantis_pagantis_checkout').setAttribute('target', 'iframe-pagantis');
    document.getElementById('pagantis_pagantis_checkout').submit();
    document.getElementById('iframe-pagantis').style.display = 'block';
    document.getElementById('paylater_myModal').style.display = 'block';
    addClass(document.getElementsByTagName('body')[0], 'paylater_modal-open')
  });
  var closeModal = function closeModal(evt) {
   evt.preventDefault();
   document.getElementById('paylater_myModal').style.display = 'none';
   removeClass(document.getElementsByTagName('body')[0], 'paylater_modal-open');
  };

  var elements = document.querySelectorAll('#paylater_close, #myModal');
   Array.prototype.forEach.call(elements, function(el){
   el.addEventListener('click', closeModal);
  });

  document.addEventListener("DOMContentLoaded", function(event) {
    document.getElementById('pagantis_pagantis_checkout').setAttribute('target', 'iframe-pagantis');
    document.getElementById('pagantis_pagantis_checkout').submit();
    document.getElementById('iframe-pagantis').style.display = 'block';
    document.getElementById('paylater_myModal').style.display = 'block';
    addClass(document.getElementsByTagName('body')[0], 'paylater_modal-open')
    });

})()
</script>

<?php
} else {
?>
  <script type="text/javascript">
    (function () {
        document.getElementById("pagantis_pagantis_checkout").submit();
    })();
  </script>
<?php
}
?>
